# Generated by Django 4.1.2 on 2022-10-19 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('cod_domicilio', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre_calle', models.CharField(blank=True, max_length=200)),
                ('numero_calle', models.BigIntegerField(blank=True)),
                ('nombre_barrio', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ZonaDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_zona', models.PositiveSmallIntegerField(unique=True)),
                ('descripcion_zona', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuil', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('apellido', models.CharField(blank=True, max_length=200)),
                ('fecha_nacimiento', models.DateField(blank=True)),
                ('email', models.CharField(blank=True, max_length=300)),
                ('domicilio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Usuario.domicilio')),
            ],
        ),
        migrations.AddField(
            model_name='domicilio',
            name='zona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Usuario.zonadomicilio'),
        ),
    ]
