# Generated by Django 4.1.2 on 2022-10-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='cod_domicilio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
