# Generated by Django 4.1.2 on 2022-10-19 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_alter_domicilio_cod_domicilio'),
    ]

    operations = [
        migrations.CreateModel(
            name='cadete',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Usuario.persona')),
                ('fecha_vigencia_carnet', models.DateField(blank=True)),
                ('numero_patente', models.CharField(blank=True, max_length=7)),
                ('fecha_ingreso', models.DateField(blank=True)),
            ],
            bases=('Usuario.persona',),
        ),
        migrations.RemoveField(
            model_name='zonadomicilio',
            name='id',
        ),
        migrations.AlterField(
            model_name='zonadomicilio',
            name='cod_zona',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
