# Generated by Django 4.1.2 on 2022-10-20 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_cadete_remove_zonadomicilio_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_telefono', models.CharField(choices=[('fijo', 'Fijo'), ('celular', 'Celular')], max_length=10)),
                ('numero', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='persona',
            name='cuil',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Usuario.telefono'),
        ),
    ]
