# Generated by Django 4.1.2 on 2022-10-21 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0004_telefono_alter_persona_cuil_persona_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='domicilio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.domicilio'),
        ),
    ]
