# Generated by Django 4.1.1 on 2022-10-24 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0005_alter_persona_domicilio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='domicilio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Usuario.domicilio'),
        ),
    ]
