# Generated by Django 4.1.1 on 2022-10-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0017_remove_estadoentrega_cadete'),
        ('Usuario', '0007_persona_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadete',
            name='pedido_cadete',
            field=models.ManyToManyField(to='Pedido.pedido'),
        ),
    ]
