# Generated by Django 4.1.1 on 2022-10-30 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0008_cadete_pedido_cadete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadete',
            name='pedido_cadete',
        ),
    ]
