# Generated by Django 3.2.4 on 2022-12-04 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0009_remove_cadete_pedido_cadete'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadete',
            name='zona_trabajo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Usuario.zonadomicilio'),
        ),
    ]
