# Generated by Django 3.2.4 on 2022-12-05 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0010_cadete_zona_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.zonadomicilio'),
        ),
    ]
