# Generated by Django 4.1.1 on 2022-10-20 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0003_cadete_remove_zonadomicilio_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_entrega', models.CharField(blank=True, max_length=1, unique=True)),
                ('descripcion_estado', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Platos',
            fields=[
                ('codigo_plato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plato', models.CharField(blank=True, max_length=200)),
                ('tipo_plato', models.CharField(blank=True, choices=[('Entrada', 'entrada'), ('Plato Principal', 'plato Principal'), ('postre', 'Postre')], max_length=100)),
                ('especialidad', models.CharField(blank=True, choices=[('Normal', 'normal'), ('Vegetariano', 'vegetariano'), ('celiaco', 'Celiaco'), ('diabetico', 'Diabetico')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('cod_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('modalidadentrega', models.CharField(blank=True, choices=[('Envio', 'envio'), ('Retiro', 'retiro')], max_length=100)),
                ('hora_entrega_desde', models.DateTimeField(blank=True)),
                ('hora_entrega_hasta', models.DateTimeField(blank=True)),
                ('estado_entrega', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Pedido.estadoentrega')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.persona')),
                ('platos', models.ManyToManyField(to='Pedido.platos')),
            ],
        ),
    ]
