# Generated by Django 4.1.1 on 2022-10-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fechapedido',
            field=models.DateField(default=False),
        ),
    ]
