# Generated by Django 4.1.1 on 2022-10-20 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_cadete_remove_zonadomicilio_id_and_more'),
        ('Pedido', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pedidos',
            new_name='Pedido',
        ),
        migrations.RenameModel(
            old_name='Platos',
            new_name='Plato',
        ),
    ]
