# Generated by Django 4.1.1 on 2022-10-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0002_rename_pedidos_pedido_rename_platos_plato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='hora_entrega_desde',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='hora_entrega_hasta',
            field=models.TimeField(blank=True),
        ),
    ]
