# Generated by Django 4.1.1 on 2022-10-20 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0003_alter_pedido_hora_entrega_desde_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(blank=True, max_length=1, unique=True)),
                ('descripcion_especialidad', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ModalidadEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modoentrega', models.CharField(blank=True, max_length=100, unique=True)),
                ('descripcion_modo_entrega', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_plato', models.CharField(blank=True, max_length=100)),
                ('descripcion_tipo_plato', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='modalidadentrega',
        ),
        migrations.AddField(
            model_name='pedido',
            name='modo_entrega',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Pedido.especialidad'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedido.especialidad'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='tipo_plato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedido.tipoplato'),
        ),
    ]
