# Generated by Django 4.1.1 on 2022-10-20 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0004_especialidad_modalidadentrega_tipoplato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='modo_entrega',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Pedido.modalidadentrega'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='especialidad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Pedido.especialidad'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='tipo_plato',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Pedido.tipoplato'),
        ),
    ]
