# Generated by Django 4.1.1 on 2022-10-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0005_alter_pedido_modo_entrega_alter_plato_especialidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='especialidad',
            field=models.CharField(max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='estadoentrega',
            name='estado_entrega',
            field=models.CharField(max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='modalidadentrega',
            name='modoentrega',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tipoplato',
            name='tipo_plato',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
