# Generated by Django 4.1.1 on 2022-10-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0006_alter_especialidad_especialidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialidad',
            name='id',
        ),
        migrations.RemoveField(
            model_name='estadoentrega',
            name='id',
        ),
        migrations.RemoveField(
            model_name='modalidadentrega',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tipoplato',
            name='id',
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='especialidad',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estadoentrega',
            name='estado_entrega',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='modalidadentrega',
            name='modoentrega',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipoplato',
            name='tipo_plato',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
