# Generated by Django 4.1.1 on 2022-10-20 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0007_remove_especialidad_id_remove_estadoentrega_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='modo_entrega',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Pedido.modalidadentrega'),
        ),
    ]
