# Generated by Django 4.1.2 on 2022-10-21 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0008_alter_pedido_modo_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='platos',
        ),
        migrations.AddField(
            model_name='pedido',
            name='platos',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Pedido.plato'),
        ),
    ]
