# Generated by Django 4.1.2 on 2022-10-21 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0009_remove_pedido_platos_pedido_platos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedido.especialidad'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='tipo_plato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedido.tipoplato'),
        ),
    ]
