# Generated by Django 4.1.2 on 2022-10-21 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0010_alter_plato_especialidad_alter_plato_tipo_plato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedido.estadoentrega'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='modo_entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedido.modalidadentrega'),
        ),
    ]
