# Generated by Django 4.1.2 on 2022-10-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0011_alter_pedido_estado_entrega_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='platos',
        ),
        migrations.AddField(
            model_name='pedido',
            name='platos',
            field=models.ManyToManyField(to='Pedido.plato'),
        ),
    ]
