# Generated by Django 4.1.2 on 2022-10-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0012_remove_pedido_platos_pedido_platos'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='estado_promocion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plato',
            name='precio_plato',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AddField(
            model_name='plato',
            name='vigencia_plato',
            field=models.BooleanField(default=True),
        ),
    ]
