# Generated by Django 4.1.2 on 2022-10-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0013_plato_estado_promocion_plato_precio_plato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='precio_plato',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8),
        ),
    ]
