# Generated by Django 4.1.1 on 2022-10-24 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0014_alter_plato_precio_plato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidad',
            options={'verbose_name': 'Especialidade'},
        ),
    ]
