# Generated by Django 4.1.1 on 2022-10-30 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0007_persona_user'),
        ('Pedido', '0015_alter_especialidad_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoentrega',
            name='cadete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuario.cadete'),
        ),
    ]
