# Generated by Django 4.1.1 on 2022-10-30 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0009_remove_cadete_pedido_cadete'),
        ('Pedido', '0017_remove_estadoentrega_cadete'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cadete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cadete', to='Usuario.cadete'),
        ),
    ]
