# Generated by Django 4.1.2 on 2022-11-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0018_pedido_cadete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='precio_plato',
            field=models.IntegerField(default=None),
        ),
    ]
